### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by ccorcos** [grayleonard/node-aubio#3]

**Comment by piem** [comment]
hi @ccorcos,

The latest version of node-aubio is at https://github.com/aubio/node-aubio

Some documentation has been added there. If it doesn't answer your (open) question, please open a new issue on [aubio/node-aubio](https://github.com/aubio/node-aubio), explaining the basics:

 - what you are trying to do
 - what you expected the software to do
 - what the software did instead

You may also want to read on [How to report bugs effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), by Simon Tatham.

cheers, piem
